#!/bin/bash

if [ $# -eq 0 ] 
then
	echo "Please enter run number"
	read RUNNUM
else
	RUNNUM=$1
fi
analyzer 'replay_coinc_new.C('$RUNNUM',-1,0,kTRUE,kFALSE,kFALSE)'
#analyzer 'replay_coinc_new.C('$RUNNUM',3000,0,kTRUE,kFALSE,kFALSE)'
#analyzer 'replay_tritium.C('$RUNNUM',3000,0,kTRUE,kFALSE,kFALSE)'
